// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBanco.Infra.Data.EF.Configurações;

#nullable disable

namespace SistemaBanco.Infra.Data.EF.Migrations
{
    [DbContext(typeof(SistemaBancoDbContext))]
    [Migration("20250909010608_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaBanco.Domain.BancoModulo.Banco", b =>
                {
                    b.Property<Guid>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoDoBanco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDoBanco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PercentualDeJuros")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BancoId");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("SistemaBanco.Domain.BoletoModulo.Boleto", b =>
                {
                    b.Property<Guid>("BoletoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CpfDoBeneficiario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CpfDoPagador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeDoBeneficiario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDoPagador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BoletoId");

                    b.HasIndex("BancoId");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("SistemaBanco.Domain.BoletoModulo.Boleto", b =>
                {
                    b.HasOne("SistemaBanco.Domain.BancoModulo.Banco", "Banco")
                        .WithMany("Boletos")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("SistemaBanco.Domain.BancoModulo.Banco", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
